# Generated by Django 4.2.17 on 2025-03-10 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('employee_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('date_created', models.DateField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_of_travel', models.CharField(max_length=100)),
                ('mode_of_travel', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('own vehicle', 'Own Vehicle'), ('ship', 'Ship')], max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_where', models.CharField(max_length=100)),
                ('to_where', models.CharField(max_length=100)),
                ('lodging', models.BooleanField(default=False)),
                ('lodging_info', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_request', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=500, null=True)),
                ('message_from_manager', models.CharField(blank=True, max_length=300, null=True)),
                ('message_from_admin', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_request', models.DateField(auto_now_add=True)),
                ('date_of_approval', models.DateField(blank=True, null=True)),
                ('date_of_rejection', models.DateField(blank=True, null=True)),
                ('date_of_revert', models.DateField(blank=True, null=True)),
                ('resubmission_request', models.BooleanField(default=False)),
                ('is_resubmitted', models.BooleanField(default=False)),
                ('status_of_request', models.CharField(choices=[('to_submit', 'To Submit'), ('submitted', 'Submitted'), ('rejected', 'Rejected'), ('reverted', 'Reverted'), ('approved', 'Approved'), ('closed', 'Closed')], default='to_submit', max_length=20)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_sent', to='requests.employee')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_received', to='requests.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
